language: node_js
node_js:
  - "stable"
service:
  - docker
before_install:
  - npm install mocha
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build and publish docker image
      script: bash docker_push
      on:
        branch: master
    - stage: test docker image
      script: docker run -rm "$DOCKER_USER"/"$DOCKER_REPO" cat hello.txt
      on:
        branch: master
after_install:
  - npm stop
stages:
  - test
  - build
  - publish
