language: node_js
node_js:
  - "stable"
service:
  - docker
before_install:
  - npm install mocha
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build and publish
      script: bash docker_push
      if: branch = master
    - stage: test docker image
      script: docker run --rm "$DOCKER_USER"/"$DOCKER_REPO" node -v
      if: branch = master
