language: node_js
node_js:
  - "stable"
service:
  - docker
jobs:
  include:
    - stage: test
      before_install:
        - npm install mocha
      script: npm test
    - stage: build_preview
      deploy:
        provider: script
        script: bash docker_push preview
      on:
        branch: master
    - stage: test_preview
      deploy:
        provider: script
        script: docker run --rm $DOCKER_USER/$DOCKER_REPO cat hello.txt
      on:
        branch: master
    - stage: publish
      deploy:
        provider: script
        script: bash docker_push latest
      on:
        branch: master
stages:
  - test
  - build_preview
  - test_preview
  - publish
