#!/bin/bash
docker build -t "$DOCKER_USER"/"$DOCKER_REPO" . && \
  docker images && \
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
  docker push "$DOCKER_USER"/"$DOCKER_REPO":$1
