#!/bin/bash
docker build -t "$DOCKER_USER"/"$DOCKER_REPO" . && \
  docker tag "$DOCKER_USER"/"$DOCKER_REPO" "$DOCKER_USER"/"$DOCKER_REPO":$1 && \
  docker images && \
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && \
  docker push "$DOCKER_USER"/"$DOCKER_REPO":$1
